name: Create Issue Branch
on:
    issues:
        types: [assigned]
    issue_comment:
        types: [created]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Set date environment variable value
          run: |
            today=$(date +'%d-%m-%Y')
            echo "DATE_VAR=$today" >> $GITHUB_ENV
        - name: Create Issue Branch
          id: Create_Issue_Branch
          uses: robvanderleek/create-issue-branch@staging
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Echo branch name (using output variable)
          run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
        - name: Set color
          id: random-color-generator
          run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
        - name: Get color
          env:
            SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
          run: echo "The selected color is $SELECTED_COLOR"
